version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key
      - DATABASE_NAME=findb_new
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=asdqwe123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=findb_new
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdqwe123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
